MAX_SUM_LEAFS = 2000
CROSS_COUNT_NORMALIZE = 10
EDGE_FEATURE_DIM = 5

EDGE_FEATURE_EMBEDDING_DIM = 16
NODE_FEATURE_EMBEDDING_DIM= 64
N_LAYERS = 7
N_EPOCHES = 60
BATCH_SIZE = 10
N_TYPES = 3
SAME_EDGE_HOST_GUEST = True
SAME_EDGE_PARENT_CHILD = False
ROOT_NODE_LEVEL = -1
VERBOSE = False
RD_SEED = 1
DROP_OUT = 0.1
JUMP_WEIGHT = -1